---
- name: "Trying Ansible."
  hosts: web
  user: ubuntu
  gather_facts: false
  tasks:
    - name: "Upgrading System"
      become: true
      apt:
        upgrade: "yes"

    # - name: "Creating a file"
    #   become: true
    #   file:
    #     path: /user/ubuntu/README.md

    - name: "Writing into the file"
      shell: |
        echo "Hello, World!" > /home/ubuntu/README.md

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
